dimensionality: 1D
name: DenseNet1D161
object:
  _target_: modules.models.DenseNet.DenseNet
  block_config:
  - 6
  - 12
  - 36
  - 24
  c_in: ${dataset.n_channels}
  c_out: ${dataset.n_classes}
  compression: 0.5
  growth_rate: 32
  ndim: 1
  num_init_features: 64
