dimensionality: 1D
name: InceptionTime10
object:
  _target_: modules.models.InceptionTime.InceptionTime
  bottleneck: true
  c_in: ${dataset.n_channels}
  c_out: ${dataset.n_classes}
  depth: 10
  kernel_size: 40
  nf: 32
  residual: true
