dimensionality: 1D
name: ResNet1D101
object:
  _target_: modules.models.ResNet.ResNet
  c_in: ${dataset.n_channels}
  c_out: ${dataset.n_classes}
  expansion: 4
  layers:
  - 3
  - 4
  - 23
  - 3
  ndim: 1
