name: M
object:
  _target_: modules.loader.create_dataloaders
  train_size: 0.8
  test_size: 0.0
  batch_size: 256
  balanced: True
  multiplier: 1
  seed: ${training.seed}
  num_workers: 8
  persistent_workers: True

